services:
  - type: web
    name: firesafe
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: "3000"
